export const REGISTERING_USER = "REGISTERING_USER";
export const USER_REGISTERED = "USER_REGISTERED";
export const REGISTERING_USER_FAILED = "REGISTERING_USER_FAILED";
export const LOGGING_USER = "LOGGING_USER";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const LOGGING_USER_FAILED = "LOGGING_USER_FAILED";
export const LOGIN_STATE = "LOGIN_STATE";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGGING_USER_OUT = "LOGGING_USER_OUT";
export const USER_TYPE = "USER_TYPE";

export const GETTING_ALL_USERS = "GETTTING_ALL_USERS";
export const GOT_ALL_USERS = "GOT_ALL_USERS";
export const GETTING_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";
export const CREATING_USER = "CREATING_USER";
export const USER_CREATED = "USER_CREATED";
export const CREATING_USER_FAILED = "CREATING_USER_FAILED";
export const DELETING_USER = "DELETING_USER";
export const USER_DELETED = "USER_DELETED";
export const DELETING_USER_FAILED = "DELETING_USER_FAILED";

export const SCANNING = "SCANNING";
export const SCAN_SUCCESS = "SCAN_SUCCESS";
export const SCAN_FAILED = "SCAN_FAILED";
export const RESET = "RESET";

export const REPORTING_SCAN = "REPORTING_SCAN";
export const REPORT_SCAN_SUCCESS = "REPORT_SCAN_SUCCESS";
export const REPORT_SCAN_FAILED = "REPORT_SCAN_FAILED";
export const APPROVING = "APPROVING";
export const APPROVED = "APPROVED";
export const APPROVING_FAILED = "APPROVING_FAILED";

export const GETTING_ALL_REPORTS = "GETTING_ALL_REPORTS";
export const GOT_ALL_REPORTS = "GOT_ALL_REPORTS";
export const GETTING_ALL_REPORTS_FAILED = "GET_ALL_REPORTS_FAILED";
